mappings:
  - as_is: true
    authors:
      - Generated 2020-04-07 17:41:05.168894
    case_sensitive: true
    display_name: fra-ipa IPA to eng-ipa IPA
    escape_special: false
    in_lang: fra-ipa
    language_name: fra-ipa
    mapping: fra-ipa_to_eng-ipa.json
    norm_form: NFD
    out_lang: eng-ipa
    reverse: false
