# To create a release:
#  - make sure /.SETUPTOOLS_SCM_PRETEND_VERSION is up to date
#  - commit the changes
#  - create an annotated tag with the version number, e.g.: git tag -a v2.0.1 -m "v2.0.1"
#  - push the tag, which will trigger this pythonpublish release workflow and hatch build will build and publish using the tag version
#  - note: only builds from tagged commits will have proper release versions, others will have dev versions

name: Publish g2p to PyPI and create a GitHub release

on:
  push:
    tags:
      # We publish only actual releases, not dev, alpha or beta versions
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate version consistency
        run: test v$(cat .SETUPTOOLS_SCM_PRETEND_VERSION) == $(echo ${{ github.ref_name }} | cut -d. -f1-2)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build tool
        run: pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
