name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    # #no-ci in the commit log flags commit we don't want CI-validated
    if: ${{ !contains(github.event.head_commit.message, '#no-ci') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pip-licenses
          if pip-licenses | grep -v 'Artistic License' | grep -v LGPL | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi
          pip install coverage coveralls
      - name: Run tests
        run: |
          coverage run --omit g2p/app.py --omit 'g2p/tests/*' --parallel-mode \
              -m gunicorn --worker-class eventlet  -w 1 g2p.app:APP --no-sendfile --bind 0.0.0.0:5000 --daemon
          sleep 5
          coverage run --omit g2p/app.py --omit 'g2p/tests/*' --parallel-mode run_tests.py dev
          pkill coverage
          sleep 5
          coverage combine
          coverage xml
          if git status | grep -E 'static.*json|mapping.*pkl'; then echo 'g2p databases out of date, please run "g2p update" and commit the results.'; false; else echo OK; fi
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false # too many upload errors to keep "true"

  test-on-windows:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '#no-ci') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run tests on Windows
        run: python run_tests.py dev
      - name: Make sure the CLI outputs utf8 on Windows
        run: |
          # Warning: This is PowerShell syntax, not bash!
          g2p convert est fra fra-ipa > out
          if (diff (echo É›) (cat out)) { throw "Output did not match reference" }
